# Generated by Django 5.2.5 on 2025-09-02 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(choices=[('bookmark', 'Bookmark'), ('search', 'Search'), ('filter', 'Filter'), ('star', 'Star'), ('heart', 'Heart'), ('folder', 'Folder'), ('tag', 'Tag'), ('clock', 'Clock'), ('eye', 'Eye'), ('lightning', 'Lightning')], default='search', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('filters', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', '-last_used'],
            },
        ),
        migrations.AddField(
            model_name='bookmark',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'is_read'], name='bookmarks_b_user_id_e6c320_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['title'], name='bookmarks_b_title_3111a2_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'domain'], name='bookmarks_b_user_id_716c27_idx'),
        ),
        migrations.AddField(
            model_name='savedview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='savedview',
            index=models.Index(fields=['user', 'order'], name='bookmarks_s_user_id_c88dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='savedview',
            index=models.Index(fields=['user', 'last_used'], name='bookmarks_s_user_id_bcf5ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedview',
            unique_together={('user', 'name')},
        ),
    ]
