# Generated by Django 4.2.1 on 2023-06-15 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('plain_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_notes', to='bookmarks.bookmark')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='bookmarks.bookmarknote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['bookmark', 'is_active'], name='bookmarks_bo_bookmar_0a8d4c_idx'), models.Index(fields=['user', 'created_at'], name='bookmarks_bo_user_id_e7f67e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookmarkSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('html_content', models.TextField()),
                ('plain_text', models.TextField()),
                ('screenshot_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='bookmarks.bookmark')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bookmark', 'created_at'], name='bookmarks_bo_bookmar_d80bd9_idx'), models.Index(fields=['status'], name='bookmarks_bo_status_9c2a0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookmarkHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('color', models.CharField(default='#FFFF00', max_length=7)),
                ('position_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='bookmarks.bookmark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bookmark', 'created_at'], name='bookmarks_bo_bookmar_41fdb3_idx'), models.Index(fields=['user', 'created_at'], name='bookmarks_bo_user_id_79a67c_idx')],
            },
        ),
    ]
