# Generated by Django 5.2.5 on 2025-09-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmarknote_bookmarksnapshot_bookmarkhighlight'),
        ('bookmarks', '0003_add_missing_fields'),
    ]

    operations = [
    ]
