# Generated by Django 4.2.1 on 2023-06-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_merge_20250902_2346'),
    ]

    operations = [
        # Make sure the Bookmark.notes field exists
        migrations.AddField(
            model_name='bookmark',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Legacy field, use bookmark_notes relationship instead'),
            preserve_default=False,
        ),

        # Then update the BookmarkNote relation to use bookmark_notes
        # This is explicitly repeated here to make sure it gets applied
        migrations.AlterField(
            model_name='bookmarknote',
            name='bookmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_notes', to='bookmarks.bookmark'),
        ),
    ]
