# Generated by Django 5.2.5 on 2025-09-02 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0006_fix_migrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='bookmarkhighlight',
            new_name='bookmarks_b_bookmar_f809d2_idx',
            old_name='bookmarks_bo_bookmar_41fdb3_idx',
        ),
        migrations.RenameIndex(
            model_name='bookmarkhighlight',
            new_name='bookmarks_b_user_id_db3792_idx',
            old_name='bookmarks_bo_user_id_79a67c_idx',
        ),
        migrations.RenameIndex(
            model_name='bookmarknote',
            new_name='bookmarks_b_bookmar_c0b1e0_idx',
            old_name='bookmarks_bo_bookmar_0a8d4c_idx',
        ),
        migrations.RenameIndex(
            model_name='bookmarknote',
            new_name='bookmarks_b_user_id_b54bd7_idx',
            old_name='bookmarks_bo_user_id_e7f67e_idx',
        ),
        migrations.RenameIndex(
            model_name='bookmarksnapshot',
            new_name='bookmarks_b_bookmar_29db9e_idx',
            old_name='bookmarks_bo_bookmar_d80bd9_idx',
        ),
        migrations.RenameIndex(
            model_name='bookmarksnapshot',
            new_name='bookmarks_b_status_aef04d_idx',
            old_name='bookmarks_bo_status_9c2a0b_idx',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', 'order'], name='bookmarks_c_user_id_6e8639_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'order'], name='bookmarks_t_user_id_6cf406_idx'),
        ),
    ]
