# Generated by Django 5.2.5 on 2025-09-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0007_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedview',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookmarkactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('visited', 'Visited'), ('favorited', 'Favorited'), ('unfavorited', 'Unfavorited'), ('archived', 'Archived'), ('unarchived', 'Unarchived'), ('merged', 'Merged')], max_length=20),
        ),
        migrations.AlterField(
            model_name='savedview',
            name='icon',
            field=models.CharField(choices=[('bookmark', 'Bookmark'), ('search', 'Search'), ('filter', 'Filter'), ('star', 'Star'), ('heart', 'Heart'), ('folder', 'Folder'), ('tag', 'Tag'), ('clock', 'Clock'), ('eye', 'Eye'), ('lightning', 'Lightning'), ('copy', 'Copy'), ('layers', 'Layers'), ('alert-triangle', 'Warning'), ('zap', 'Zap')], default='search', max_length=20),
        ),
    ]
