# Generated by Django 5.2.5 on 2025-09-03 09:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0009_boardlayout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='bookmarks.bookmark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['user', 'visited_at'], name='bookmarks_b_user_id_f452e0_idx'), models.Index(fields=['bookmark', 'visited_at'], name='bookmarks_b_bookmar_281d24_idx')],
            },
        ),
    ]
