# Generated by Django 5.2.5 on 2025-09-03 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0010_bookmarkhistoryentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('redirected', 'Redirected'), ('broken', 'Broken'), ('pending', 'Pending Check'), ('archived', 'Web Archive Available')], default='pending', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('next_check', models.DateTimeField(blank=True, null=True)),
                ('final_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_time', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('archive_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('check_count', models.PositiveIntegerField(default=0)),
                ('bookmark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='bookmarks.bookmark')),
            ],
            options={
                'ordering': ['-last_checked'],
                'indexes': [models.Index(fields=['status'], name='bookmarks_l_status_7f1c79_idx'), models.Index(fields=['last_checked'], name='bookmarks_l_last_ch_c24e19_idx'), models.Index(fields=['next_check'], name='bookmarks_l_next_ch_e7f36c_idx')],
            },
        ),
        migrations.CreateModel(
            name='BulkActionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('tag', 'Add Tags'), ('untag', 'Remove Tags'), ('move', 'Move to Collection'), ('archive', 'Archive'), ('unarchive', 'Unarchive'), ('favorite', 'Favorite'), ('unfavorite', 'Unfavorite'), ('delete', 'Delete'), ('mark_read', 'Mark as Read'), ('mark_unread', 'Mark as Unread'), ('check_health', 'Check Link Health'), ('export', 'Export'), ('merge', 'Merge Duplicates')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('bookmark_ids', models.JSONField(default=list)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='bookmarks_b_user_id_4de55b_idx'), models.Index(fields=['status', 'created_at'], name='bookmarks_b_status_61d79c_idx')],
            },
        ),
    ]
